name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # MSBuild e aplicações desktop precisam de ambiente Windows.

    env:
      Solution_Name: ./Agenda.sln
      Test_Project_Path: ./Agenda.DAL.Test/Agenda.DAL.Test.csproj
      Wap_Project_Directory: ./Agenda.Package
      Wap_Project_Path: ./Agenda.Package/Agenda.Package.wapproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Instalar o .NET Core workload
    - name: Instalar .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Adicionar MSBuild ao PATH
    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v2

    # Garantir que o diretório Wap_Project_Directory existe
    - name: Criar diretório WAP se não existir
      run: |
        if (-Not (Test-Path $env:Wap_Project_Directory)) {
          mkdir $env:Wap_Project_Directory
        }

    # Executar testes de un
