name: .NET 8 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Debug file paths
      run: |
        pwd
        ls -R

    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore ./Agenda.sln

    - name: Build project
      run: dotnet build ./Agenda.sln --configuration Release --no-restore

    - name: Run tests
       shell: bash
       run: dotnet test ./Agenda.DAL.Test/Agenda.DAL.Test.csproj --no-restore --no-build --configuration Release --verbosity detailed --logger "trx;LogFileName=test_results.trx"

    - name: Display test results
       run: cat ./TestResults/test_results.trx || echo "Test report not found"

    - name: Validate test results
       run: |
         if [ $? -ne 0 ]; then
           echo "Test run failed. Exiting..."
           exit 1
         fi 

    - name: Upload code coverage result
      uses: codecov/codecov-action@v3
      with:
        files: ./TestResults/*.xml
        fail_ci_if_error: true        